export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
      <header
        style={{
          padding: '1rem',
          backgroundColor: 'black',
          color: 'white',
          textAlign: 'center',
        }}
      > 
        <p > This is a header</p></header>
        {children}
        
      <footer 
        style={{
          padding: '1rem',
          backgroundColor: 'black',
          color: 'white',
          textAlign: 'center',
        }}
      ><p>@2024 by selani didulani</p>
      
        </footer>  
      </body>
    </html>
  )
}
